### ISSUE TITLE
taka mała korekta dla kroku instrukcji "Zainstalować .net core SDK"

### ISSUE THREAD

**Issue by j00zek** [pogarek/SzczepLookup#1]
wygląda na to, że musi to być Zainstalować .net core SDK 3.1, z nowszym zgłasza błąd.

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64

**Comment by pogarek** [comment]
.net core SDK  3.1 , tak.  W pliku .csproj jest:
```
 <TargetFramework>netcoreapp3.1</TargetFramework>
```

Jakiego SDK próbowałeś ?

**Comment by pogarek** [comment]
Dobra, zainstalowałeś .net 5.0 
![image](https://user-images.githubusercontent.com/8302383/116854030-5538f500-abf7-11eb-8111-3f36f99a65a4.png)

Zamiast .net core.

**Comment by j00zek** [comment]
po zainstalowaniu tego co podpowiedział zadziałało, brakuje mi statusu ale bez trybu verbose. cyli jak szuka a nie znajdzie to info, że szukał i nic nie znalazł

**Comment by pogarek** [comment]
Wg mnie tak robi. Co Ci program wypisuje ? U mnie jest : 

``
10:10 Brak terminow na (cov19.pfizer,cov19.moderna) na ta chwile. Szukanie w wojewodztwie wlaczone: False Wszystkie szczepionki: False. Pierwszy termin bez filtra na szczepionki: 23.05.2021 08:45:00 cov19.astra_zeneca
``

**Comment by j00zek** [comment]
być może to moja niewiedza. Ale pomiędzy uruchomieniem a pierwszą informacją minęło sporo czasu i myślałem, że nic nie znalazł.
s:\SzczepLookup-main>dotnet run
Odśwież przeglądarce: https://pacjent.erejestracja.ezdrowie.gov.pl/wizyty  , zaloguj się (jeśli trzeba) i wciśnij enter


Listening on 'ExplicitProxyEndPoint' endpoint at Ip 0.0.0.0 and port: 8000
Set endpoint at Ip 0.0.0.0 and port: 8000 as System HTTP and HTTPS Proxy
Odśwież przeglądarke : https://pacjent.erejestracja.ezdrowie.gov.pl/wizyty. Jeśli podano numer telefonu w config.json sprawdz czy profil w portalu jest zgodny z numerem telefonu
======> 10:03 26.05.2021 11:30:00 cov19.pfizer Punkt Szczepień Powszechnych - OSP w Szczytnie Szczytno 11a, Szczytno
======> 10:05 21.05.2021 12:00:00 cov19.pfizer Gabinet diagnostyczno-zabiegowy Nr 13 - MAZOWIECKI SZPITAL SPECJALISTYCZNY SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ ul. Juliana Aleksandrowicza 5, Radom
======> 10:07 04.05.2021 14:10:00 cov19.pfizer CENTRUM MEDYCZNE STAY HEALTHY Kłobucka 8A lok. U4, Warszawa
======> 10:09 19.05.2021 12:00:00 cov19.pfizer Centrum Medyczne Petra Medica Filia nr 4 Cisowa 7, Drężewo
======> 10:12 19.05.2021 12:00:00 cov19.pfizer Centrum Medyczne Petra Medica Filia nr 4 Cisowa 7, Drężewo

**Comment by j00zek** [comment]
dobra, teraz mi wyświetlił :)
10:14 Brak terminow na (cov19.pfizer,cov19.moderna) na tą chwilę. Szukanie w wojewodztwie włączone: True Wszystkie szczepionki: False. Pierwszy termin bez filtra na szczepionki: 23.05.2021 08:45:00 cov19.astra_zeneca

**Comment by pogarek** [comment]
Spoko. Czyli coś jest dostępne . 
===> Oznacz, że znaleziona wizyta jest w widełkach czasowych. Z BookMode umówiłby pierwszą z nich .  Fajnie że działa. Powodzenia !!!

**Comment by j00zek** [comment]
superancko, jeszcze takie pytanie. Powiedzmy, że znajdzie kilka wizyt  kilku miejscach. Która wybierze? pierwszą zwróconą, czy najbliższą?

**Comment by pogarek** [comment]
Sortuje to co znalazł po dacie/czasie i bierze pierwszą. Jeśli o tej samej godzinie i dacie są dwie wizyty, to weźmie , którąś, z z nich: https://github.com/pogarek/SzczepLookup/blob/main/Program.cs#L272
